// import type { Metadata } from 'next';
// import { ClerkProvider } from '@clerk/nextjs';
// import { Plus_Jakarta_Sans } from 'next/font/google';
// import './globals.css';
// import { Toaster } from '@/components/ui/toaster';
// import { ThemeProvider } from '@/context/them-provider';
// import { Analytics } from '@vercel/analytics/react';

// const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Amplifier AI',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={jakarta.className}>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="light"
//             disableTransitionOnChange
//           >
//             {children}
//             <Toaster />
//             <Analytics />
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }

import { ClerkProvider } from '@clerk/nextjs';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/context/them-provider';
import { Analytics } from '@vercel/analytics/react';

const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Amplifier AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={jakarta.className}>
          <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
            {children}
            <Toaster />
            <Analytics />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}